stages:
  - build

compile_resume:
  stage: build
  image: docker:latest   # Use the Docker executor
  services:
    - docker:dind   # Enable Docker-in-Docker for building the LaTeX Docker image
  script:
    - docker build -t latex-resume .
    - docker run --rm -v $(pwd):/output latex-resume
  artifacts:
    paths:
      - resume.pdf

