name: LaTeX Build

on:
  push:
    branches:
      - '*'  # Run on all branches

jobs:
  compile_resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          pdflatex -interaction=nonstopmode -halt-on-error resume.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: resume
          path: resume.pdf
